import { ARCANE_CLUSTER_ELEMENTS, COMBINABLE_ELEMENTS, type ElementType, type RarityType } from "./arkynConstants";

export interface SigilDefinition {
    id: string;
    name: string;
    rarity: RarityType;
    description: string;
    cost: number;
    sellPrice: number;
    /**
     * Optional explainer shown in the tooltip below the description — a
     * small row of element rune icons with a label. Used when a sigil's
     * effect only applies to a specific element group (e.g. Fuze only
     * fuses Elemental runes, not Arcane) and the scope isn't obvious
     * from the description alone.
     */
    explainer?: {
        label?: string;
        elements: readonly ElementType[];
    };
}

export const SIGIL_DEFINITIONS: Record<string, SigilDefinition> = {
    voltage: {
        id: "voltage",
        name: "Voltage",
        rarity: "uncommon",
        description: "Lightning runes have a {1 in 4} chance to hit twice.",
        cost: 4,
        sellPrice: 2,
    },
    burnrite: {
        id: "burnrite",
        name: "Burnrite",
        rarity: "uncommon",
        description: "Unlocks {Fire + Death} spell synergy.",
        cost: 4,
        sellPrice: 2,
    },
    caster: {
        id: "caster",
        name: "Caster",
        rarity: "common",
        description: "{+1 Cast} per round.",
        cost: 3,
        sellPrice: 1,
    },
    synapse: {
        id: "synapse",
        name: "Synapse",
        rarity: "rare",
        description: "Each held Psy rune adds {+2 Mult} to your casts.",
        cost: 6,
        sellPrice: 3,
    },
    fortune: {
        id: "fortune",
        name: "Fortune",
        rarity: "uncommon",
        description: "Critical runes have a {1 in 3} chance to grant {+2 gold}.",
        cost: 4,
        sellPrice: 2,
    },
    fuze: {
        id: "fuze",
        name: "Fuze",
        rarity: "rare",
        description: "Any {2} Elemental runes can fuse into a {Combo spell}.",
        cost: 6,
        sellPrice: 3,
        explainer: {
            label: "Elemental runes:",
            elements: COMBINABLE_ELEMENTS,
        },
    },
    hourglass: {
        id: "hourglass",
        name: "Hourglass",
        rarity: "rare",
        description: "Played runes have a {1 in 4} chance to retrigger once.",
        cost: 6,
        sellPrice: 3,
    },
    thief: {
        id: "thief",
        name: "Thief",
        rarity: "common",
        description: "Gain a random {Scroll} at the start of each round.",
        cost: 3,
        sellPrice: 1,
    },
    supercell: {
        id: "supercell",
        name: "Supercell",
        rarity: "rare",
        description: "Lightning and Air spells gain {x3 Mult}.",
        cost: 6,
        sellPrice: 3,
        explainer: {
            label: "Applies to:",
            elements: ["lightning", "air"] as const,
        },
    },
    eruption: {
        id: "eruption",
        name: "Eruption",
        rarity: "uncommon",
        description: "Fire and Earth spells gain {x3 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["fire", "earth"] as const,
        },
    },
    impale: {
        id: "impale",
        name: "Impale",
        rarity: "common",
        description: "{Steel} runes ignore enemy resistance.",
        cost: 3,
        sellPrice: 1,
        explainer: {
            label: "Applies to:",
            elements: ["steel"] as const,
        },
    },
    plunder: {
        id: "plunder",
        name: "Plunder",
        rarity: "common",
        description: "Earn {+5 Gold} at the end of each round.",
        cost: 3,
        sellPrice: 1,
    },
    arcana: {
        id: "arcana",
        name: "Arcana",
        rarity: "uncommon",
        description: "Each played {Arcane Cluster} rune adds {+2 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Arcane Cluster runes:",
            elements: ARCANE_CLUSTER_ELEMENTS,
        },
    },
    lex_divina: {
        id: "lex_divina",
        name: "Lex Divina",
        rarity: "uncommon",
        description: "{Holy} runes gain {+8 Base} and {+2 Mult} on Critical hits.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["holy"] as const,
        },
    },
    engine: {
        id: "engine",
        name: "Engine",
        rarity: "common",
        description: "{Steel} runes gain {+4 Base} and {+2 Mult}.",
        cost: 3,
        sellPrice: 1,
        explainer: {
            label: "Applies to:",
            elements: ["steel"] as const,
        },
    },
    scroll_god: {
        id: "scroll_god",
        name: "Scroll God",
        rarity: "uncommon",
        description: "Scrolls grant {+2 levels} instead of +1.",
        cost: 4,
        sellPrice: 2,
    },
    executioner: {
        id: "executioner",
        name: "Executioner",
        rarity: "rare",
        description: "Gain [[+0.1x Mult]] per Critical Hit.",
        cost: 6,
        sellPrice: 3,
    },
    binoculars: {
        id: "binoculars",
        name: "Binoculars",
        rarity: "common",
        description: "Disable {one random enemy resistance} each round.",
        cost: 3,
        sellPrice: 1,
    },
    haphazard: {
        id: "haphazard",
        name: "Haphazard",
        rarity: "rare",
        description: "Play {all unique} runes to cast {Abomination}. {Tier} equals runes played. {-1 Hand Size}.",
        cost: 6,
        sellPrice: 3,
    },
    elixir: {
        id: "elixir",
        name: "Elixir",
        rarity: "common",
        description: "Gain {+Mult} equal to the total {Sell value} of your Sigils.",
        cost: 3,
        sellPrice: 1,
    },
    spellcaster: {
        id: "spellcaster",
        name: "Spellcaster",
        rarity: "common",
        description: "{+5 Mult} to every cast.",
        cost: 3,
        sellPrice: 1,
    },
    zephyr: {
        id: "zephyr",
        name: "Zephyr",
        rarity: "uncommon",
        description: "Air spells gain {x2 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["air"] as const,
        },
    },
    banish: {
        id: "banish",
        name: "Banish",
        rarity: "uncommon",
        description: "If your {first discard} is one rune, {destroy it} and gain {+4 Gold}.",
        cost: 4,
        sellPrice: 2,
    },
    magic_mirror: {
        id: "magic_mirror",
        name: "Magic Mirror",
        rarity: "rare",
        description: "If your {first cast} is one rune, {duplicate it} into your hand.",
        cost: 6,
        sellPrice: 3,
    },
    mimic: {
        id: "mimic",
        name: "Mimic",
        rarity: "rare",
        description: "Copies the {Sigil effect} to the right.",
        cost: 6,
        sellPrice: 3,
    },
    ahoy: {
        id: "ahoy",
        name: "Ahoy!",
        rarity: "uncommon",
        description: "Earn {+5 Gold} for each discarded {rune} of this round's element.",
        cost: 4,
        sellPrice: 2,
    },
    chainlink: {
        id: "chainlink",
        name: "Chainlink",
        rarity: "uncommon",
        description: "{Retrigger all played runes} on the {final hand}.",
        cost: 4,
        sellPrice: 2,
    },
    tectonic: {
        id: "tectonic",
        name: "Tectonic",
        rarity: "common",
        description: "{Tier IV} spells gain {+10 Mult}.",
        cost: 3,
        sellPrice: 1,
    },
    boom_bomb: {
        id: "boom_bomb",
        name: "Boom Bomb",
        rarity: "common",
        description: "Each cast, roll a random {Mult bonus} from {0, 2, 4, 8, or 16}.",
        cost: 3,
        sellPrice: 1,
    },
    alkahest: {
        id: "alkahest",
        name: "Alkahest",
        rarity: "uncommon",
        description: "{Poison} and {Arcane} runes gain {+10 Base} and {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["poison", "arcane"] as const,
        },
    },
    blackjack: {
        id: "blackjack",
        name: "Blackjack",
        rarity: "rare",
        description: "{Death} runes have a {1 in 21} chance to {execute} the enemy.",
        cost: 6,
        sellPrice: 3,
        explainer: {
            label: "Applies to:",
            elements: ["death"] as const,
        },
    },
    big_bang: {
        id: "big_bang",
        name: "Big Bang",
        rarity: "rare",
        description: "Each played rune multiplies damage: {x1} → {x1.5} → {x2} → {x2.5} → {x3}. {-2 Hand Size}.",
        cost: 6,
        sellPrice: 3,
    },
    orwyns_spellbook: {
        id: "orwyns_spellbook",
        name: "Orwyn's Spellbook",
        rarity: "uncommon",
        description: "{+2 Hand Size} {-1 Cast}.",
        cost: 4,
        sellPrice: 2,
    },
    keychain: {
        id: "keychain",
        name: "Keychain",
        rarity: "common",
        description: "Retrigger the {first played rune} that {critical hits} {2 additional times}.",
        cost: 3,
        sellPrice: 1,
    },
    golem: {
        id: "golem",
        name: "Golem",
        rarity: "uncommon",
        description: "{Earth} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["earth"] as const,
        },
    },
    gale: {
        id: "gale",
        name: "Gale",
        rarity: "uncommon",
        description: "{Air} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["air"] as const,
        },
    },
    shade: {
        id: "shade",
        name: "Shade",
        rarity: "uncommon",
        description: "{Shadow} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["shadow"] as const,
        },
    },
    stormfist: {
        id: "stormfist",
        name: "Stormfist",
        rarity: "uncommon",
        description: "{Lightning} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["lightning"] as const,
        },
    },
    cadaver: {
        id: "cadaver",
        name: "Cadaver",
        rarity: "uncommon",
        description: "{Death} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["death"] as const,
        },
    },
    metallurgy: {
        id: "metallurgy",
        name: "Metallurgy",
        rarity: "uncommon",
        description: "{Steel} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["steel"] as const,
        },
    },
    mystique: {
        id: "mystique",
        name: "Mystique",
        rarity: "uncommon",
        description: "{Arcane} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["arcane"] as const,
        },
    },
    psychic: {
        id: "psychic",
        name: "Psychic",
        rarity: "uncommon",
        description: "{Psy} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["psy"] as const,
        },
    },
    icicle: {
        id: "icicle",
        name: "Icicle",
        rarity: "uncommon",
        description: "{Ice} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["ice"] as const,
        },
    },
    cyanide: {
        id: "cyanide",
        name: "Cyanide",
        rarity: "uncommon",
        description: "{Poison} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["poison"] as const,
        },
    },
    angelic: {
        id: "angelic",
        name: "Angelic",
        rarity: "uncommon",
        description: "{Holy} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["holy"] as const,
        },
    },
    fireball: {
        id: "fireball",
        name: "Fireball",
        rarity: "uncommon",
        description: "{Fire} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["fire"] as const,
        },
    },
    tidal_wave: {
        id: "tidal_wave",
        name: "Tidal Wave",
        rarity: "uncommon",
        description: "{Water} runes give {+4 Mult}.",
        cost: 4,
        sellPrice: 2,
        explainer: {
            label: "Applies to:",
            elements: ["water"] as const,
        },
    },
};

export const SIGIL_IDS = Object.keys(SIGIL_DEFINITIONS);
